# Generated by Django 5.0.7 on 2025-04-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
    ]
