# Generated by Django 5.0.7 on 2025-04-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_department_doctor_medicine_patient_staff_systemlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='billingitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nurseduty',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'managed': False},
        ),
    ]
