# Generated by Django 5.0.7 on 2025-04-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_alter_appointment_options_alter_billing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billingitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nurseduty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={},
        ),
    ]
